import { Controller, Get, Post, Body, Patch, Param, Delete, Query, HttpStatus, HttpCode, UseGuards } from '@nestjs/common';
import { AiService } from './ai.service';
import { CreateAiDto } from './dto/create-ai.dto';
import { UpdateAiDto } from './dto/update-ai.dto';
import { PromptDto } from './dto/prompt-ai.dto';
import { ApiAcceptedResponse, ApiBadRequestResponse, ApiForbiddenResponse, ApiInternalServerErrorResponse, ApiOkResponse, ApiOperation, ApiUnauthorizedResponse } from '@nestjs/swagger';
import { BearerTokenGuard } from 'src/auth/guard/bearer-token.guard';

@Controller('/api/ai')
@UseGuards(BearerTokenGuard)
@ApiUnauthorizedResponse({
  description:
    "Happen because the user is not authorized (doesn't have a valid access token)",
  example: {
    message: "Unauthorized",
    data: null,
  },
})
@ApiForbiddenResponse({
  description:
    "Happen because the user doesn't have the right role to access this endpoint",
  example: {
    message: "Forbidden resource",
    data: null,
  },
})
@ApiInternalServerErrorResponse({
  description:
    "Happen when something went wrong, that is not handled by this API, e.g. database error",
  example: {
    message: "Internal Server Error",
    data: null,
  },
})
export class AiController {
  constructor(private readonly aiService: AiService) {}

  @Post()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: "Request response for evaluating essay",
    description: "Requesting a response from gemini for evaluating essay",
  })
  @ApiOkResponse({
    description: "The response was successfully generated by the model and returned.",
    example: {
      messages: "Data fetched successfully from gemini-1.5-flash",
      data: {
        "suggestion": "This essay demonstrates a heartfelt understanding of family, but the writing needs improvement.  Grammar issues include comma splices (e.g., \"My mom, she always cook\"), subject-verb agreement (\"I think he very annoying\"), and run-on sentences.  Focus on stronger sentence structure and precise vocabulary. Expand on specific examples to create a more engaging narrative.  Explore the complexities of family relationships beyond simple statements of love and support. Consider using more descriptive language to evoke emotion.  For instance, instead of 'I feel better,' describe the comforting feeling of your mother's cooking.  Practice using more advanced sentence structures to enhance fluency and sophistication. Improving these areas will elevate the essay to a higher standard.",
        "score": 70
      }
    }
  })
  @ApiBadRequestResponse({
    description: "Bad request, e.g. missing required fields",
    example: {
      "messages": [
        "theme must be a string",
        "essay must be a string"
      ],
      "data": null
    }
  })
  async getGeminiData(@Body() promptDto: PromptDto) {
    // Pass the DTO to the service
    const {modelName, data} = await this.aiService.fetchGeminiData(promptDto);

    return {
      messages: `Data fetched successfully from ${modelName}`,
      data,
    };
  }
}