services:
  backend:
    build:
      context: ./dolphin-streak-backend
      dockerfile: Dockerfile
    container_name: dolphin-streak-backend
    ports:
      - "8102:8102"  # Public port 8102 maps to container port 3000
    env_file:
      - ./dolphin-streak-backend/.env  # Contains MongoDB Atlas URI
    command: sh -c "npm run build && npm run start:prod -- --host 0.0.0.0"
    networks:
      - app-network

  frontend:
    build:
      context: ./dolphin-streak-frontend
      dockerfile: Dockerfile
    container_name: dolphin-streak-frontend
    ports:
      - "3000:3000"  # Direct port mapping
    env_file:
      - ./dolphin-streak-frontend/.env
    command: sh -c "npm run build && npm run start -- -H 0.0.0.0"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge